image: elivz/dev-utils

variables:
  SSH_USER: changeme
  LIVE_DOMAIN: changeme.com
  LIVE_ROOT: /var/www/public_html
  STAGING_DOMAIN: changeme.com
  STAGING_ROOT: /var/www/staging_html
  CACHE_CLEAR_URI: /actions/cacheClear/clear?key=xxyyzz

cache:
  paths:
    - node_modules

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - yarn
  - yarn build

stage_deploy:
  stage: deploy
  only:
    - develop
  artifacts:
    paths:
      - build/
  script:
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - rsync -chaz --stats --delete --exclude 'craft/storage' --exclude 'public_html/media' --exclude '.env.php' build/dist/ ${SSH_USER}@${STAGING_DOMAIN}:${STAGING_ROOT}
    - wget -qO- http://${STAGING_DOMAIN}${CACHE_CLEAR_URI}

live_deploy:
  stage: deploy
  only:
    - master
  script:
    - ssh-add <(echo "$LIVE_PRIVATE_KEY")
    - rsync -chaz --stats --delete --exclude 'craft/storage' --exclude 'public_html/media' --exclude '.env.php' build/dist/ ${SSH_USER}@${LIVE_DOMAIN}:${LIVE_ROOT}
    - wget -qO- http://${LIVE_DOMAIN}${CACHE_CLEAR_URI}
