image: elivz/dev-utils

variables:
  SSH_USER: changeme
  DOMAIN: changeme.com
  LIVE_ROOT: /var/www/public_html
  STAGING_ROOT: /var/www/staging_html
  CACHE_CLEAR_KEY: xxyyzz

cache:
  paths:
    - node_modules

before_script:
  - yarn
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build:
  - yarn build

stage_deploy:
  artifacts:
    paths:
      - build/
  only:
    - develop
  script:
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - rsync -chaz --stats --delete --exclude 'craft/storage' --exclude 'public_html/media' --exclude '.env.php' build/dist/ ${SSH_USER}@${DOMAIN}:${STAGING_ROOT}
    - wget -qO- http://staging.${DOMAIN}/actions/cacheClear/clear?key=${CACHE_CLEAR_KEY}

live_deploy:
  artifacts:
    paths:
      - build/
  only:
    - develop
  script:
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - rsync -chaz --stats --delete --exclude 'craft/storage' --exclude 'public_html/media' --exclude '.env.php' build/dist/ ${SSH_USER}@${DOMAIN}:${LIVE_ROOT}
    - wget -qO- http://${DOMAIN}/actions/cacheClear/clear?key=${CACHE_CLEAR_KEY}
