image: elivz/php

variables:
  LIVE_SSH_USER: REPLACE_ME
  LIVE_DOMAIN: REPLACE_ME
  LIVE_ROOT: /var/www/public_html
  STAGING_SSH_USER: REPLACE_ME
  STAGING_DOMAIN: REPLACE_ME
  STAGING_ROOT: /var/www/staging_html
  CACHE_CLEAR_URI: /actions/cacheClear/clear?key=REPLACE_ME

cache:
  paths:
    - node_modules

before_script:
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - yarn
  - yarn build
  - composer update

stage_deploy:
  stage: deploy
  only:
    - develop
  artifacts:
    paths:
      - build/
  script:
    - rsync -chaz --stats --delete --exclude 'craft/storage' --exclude 'public_html/media' --exclude '.env.php' build/dist/ ${STAGING_SSH_USER}@${STAGING_DOMAIN}:${STAGING_ROOT}
    - wget -qO- http://${STAGING_DOMAIN}${CACHE_CLEAR_URI}

live_deploy:
  stage: deploy
  only:
    - master
  script:
    - rsync -chaz --stats --delete --exclude 'craft/storage' --exclude 'public_html/media' --exclude '.env.php' build/dist/ ${LIVE_SSH_USER}@${LIVE_DOMAIN}:${LIVE_ROOT}
    - wget -qO- http://${LIVE_DOMAIN}${CACHE_CLEAR_URI}
