version: '2'

services:
  web:
    build:
      context: ./docker
      args:
        # Set the public folder name here (e.g. /public_html, or '' to use /dist as the root)
        public: /public_html
    ports:
      - "80:80"
    volumes:
      - ./dist:/var/www
    links:
      - mysql
      - mail

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: r3mN430YmnDKxePd3lrbciHK1
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: "123"

  mail:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

volumes:
  data: {}
