version: '3'

services:
  php:
    build:
      context: ./config
      args:
        # Set the public folder name here (e.g. /public_html, or '' to use /dist as the root)
        PUBLIC: /public_html
    ports:
      - "8080:80"
    volumes:
      - ./dist:/var/www
    depends_on:
      - db
      - mail
    environment:
      DB_HOST: mysql
      DB_NAME: app
      DB_USER: app
      DB_PASS: 123
      BASE_URL: http://localhost:8080

  db:
    image: mariadb
    ports:
      - "4306:3306"
    volumes:
      - ./config/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: "123"
      MYSQL_ROOT_PASSWORD: password

  mail:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
