version: '3'

services:
  web:
    image: elivz/php
    ports:
      - "8080:80"
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ..:/var/www
    environment:
      # Don't change these
      DB_HOST:
      DB_NAME:
      DB_USER:
      DB_PASS:
      BASE_URL:
      PUBLIC_FOLDER: /dist${PUBLIC_FOLDER}
      IP:

  db:
    image: mariadb
    ports:
      - "4306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: password

  mail:
    image: tophfr/mailcatcher
    ports:
      - "1080:80"
