version: '3'

services:
  web:
    image: elivz/php
    ports:
      - "80:80"
      - "8080:80"
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ..:/var/www
    links:
      - db
      - mail
    environment:
      DB_HOST: db
      DB_NAME: app
      DB_USER: app
      DB_PASS: 123
      BASE_URL: http://localhost
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Don't change these
      IP:
      PUBLIC_FOLDER:
    tty: true

  db:
    image: mariadb
    ports:
      - "4306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: 123
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: password

  mail:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
