version: '3'

services:
  php:
    image: elivz/php
    ports:
      - "8080:80"
    volumes:
      - ../dist:/var/www
    depends_on:
      - db
      - mail
    restart: always
    environment:
      PUBLIC_FOLDER:
      DB_HOST: mysql
      DB_NAME: app
      DB_USER: app
      DB_PASS: 123
      BASE_URL: http://localhost:8080

  db:
    image: mariadb
    ports:
      - "4306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: "123"
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: password

  mail:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
